"""added the file_name in the scanned_images

Revision ID: 2c6aee35cb30
Revises: b9112a3b0163
Create Date: 2026-01-04 23:50:59.615203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6aee35cb30'
down_revision: Union[str, Sequence[str], None] = 'b9112a3b0163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scanned_images', sa.Column('file_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scanned_images', 'file_name')
    # ### end Alembic commands ###
