"""removed the unique constrains

Revision ID: 632d2455cd15
Revises: eec3ff0bbb43
Create Date: 2026-01-21 04:42:39.320304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '632d2455cd15'
down_revision: Union[str, Sequence[str], None] = 'eec3ff0bbb43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hf_models_model_id'), table_name='hf_models')
    op.create_index(op.f('ix_hf_models_model_id'), 'hf_models', ['model_id'], unique=False)
    op.drop_index(op.f('ix_hf_models_model_provider'), table_name='hf_models')
    op.create_index(op.f('ix_hf_models_model_provider'), 'hf_models', ['model_provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hf_models_model_provider'), table_name='hf_models')
    op.create_index(op.f('ix_hf_models_model_provider'), 'hf_models', ['model_provider'], unique=True)
    op.drop_index(op.f('ix_hf_models_model_id'), table_name='hf_models')
    op.create_index(op.f('ix_hf_models_model_id'), 'hf_models', ['model_id'], unique=True)
    # ### end Alembic commands ###
