"""create hf_models table

Revision ID: 68fd6f506284
Revises: 1c1ec15cd702
Create Date: 2026-01-04 08:38:41.861529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68fd6f506284'
down_revision: Union[str, Sequence[str], None] = '1c1ec15cd702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hf_models',
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('hf_model_id', sa.String(length=255), nullable=False),
    sa.Column('hf_url', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=True),
    sa.Column('medical_domain', sa.String(length=100), nullable=True),
    sa.Column('modality', sa.String(length=100), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('auc_score', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('trained_on_dataset', sa.String(length=255), nullable=True),
    sa.Column('dataset_url', sa.Text(), nullable=True),
    sa.Column('architecture', sa.String(length=100), nullable=True),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('parameters_millions', sa.String(length=50), nullable=True),
    sa.Column('inference_type', sa.String(length=50), nullable=True),
    sa.Column('supports_batch', sa.Boolean(), nullable=False),
    sa.Column('max_input_size', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('revision', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_experimental', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hf_models_hf_model_id'), 'hf_models', ['hf_model_id'], unique=True)
    op.create_index(op.f('ix_hf_models_id'), 'hf_models', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hf_models_id'), table_name='hf_models')
    op.drop_index(op.f('ix_hf_models_hf_model_id'), table_name='hf_models')
    op.drop_table('hf_models')
    # ### end Alembic commands ###
