"""Updated the models

Revision ID: 87f0479a2cea
Revises: 1b106581f6f9
Create Date: 2026-01-04 20:01:33.567903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f0479a2cea'
down_revision: Union[str, Sequence[str], None] = '1b106581f6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message', 'model_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message', 'model_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
