"""removed the url

Revision ID: a3df4cf59093
Revises: 872ce61f76b9
Create Date: 2026-01-05 00:09:55.735546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3df4cf59093'
down_revision: Union[str, Sequence[str], None] = '872ce61f76b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scanned_images', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scanned_images', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
