"""Added the order and updated the hf model

Revision ID: eec3ff0bbb43
Revises: d1855083445b
Create Date: 2026-01-05 19:41:36.986405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec3ff0bbb43'
down_revision: Union[str, Sequence[str], None] = 'd1855083445b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('polar_order_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('polar_order_id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.add_column('hf_models', sa.Column('model_id', sa.String(length=255), nullable=False))
    op.add_column('hf_models', sa.Column('model_provider', sa.String(length=255), nullable=False))
    op.add_column('hf_models', sa.Column('model_url', sa.Text(), nullable=True))
    op.add_column('hf_models', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_hf_models_hf_model_id'), table_name='hf_models')
    op.create_index(op.f('ix_hf_models_model_id'), 'hf_models', ['model_id'], unique=True)
    op.create_index(op.f('ix_hf_models_model_provider'), 'hf_models', ['model_provider'], unique=True)
    op.drop_column('hf_models', 'revision')
    op.drop_column('hf_models', 'full_description')
    op.drop_column('hf_models', 'hf_url')
    op.drop_column('hf_models', 'f1_score')
    op.drop_column('hf_models', 'auc_score')
    op.drop_column('hf_models', 'architecture')
    op.drop_column('hf_models', 'supports_batch')
    op.drop_column('hf_models', 'short_description')
    op.drop_column('hf_models', 'modality')
    op.drop_column('hf_models', 'precision')
    op.drop_column('hf_models', 'model_version')
    op.drop_column('hf_models', 'parameters_millions')
    op.drop_column('hf_models', 'hf_model_id')
    op.drop_column('hf_models', 'framework')
    op.drop_column('hf_models', 'recall')
    op.drop_column('hf_models', 'max_input_size')
    op.add_column('users', sa.Column('polar_customer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_polar_customer_id'), 'users', ['polar_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_polar_customer_id'), table_name='users')
    op.drop_column('users', 'polar_customer_id')
    op.add_column('hf_models', sa.Column('max_input_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('hf_models', sa.Column('recall', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('hf_models', sa.Column('framework', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('hf_models', sa.Column('hf_model_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('hf_models', sa.Column('parameters_millions', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('hf_models', sa.Column('model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('hf_models', sa.Column('precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('hf_models', sa.Column('modality', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('hf_models', sa.Column('short_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('hf_models', sa.Column('supports_batch', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('hf_models', sa.Column('architecture', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('hf_models', sa.Column('auc_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('hf_models', sa.Column('f1_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('hf_models', sa.Column('hf_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('hf_models', sa.Column('full_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('hf_models', sa.Column('revision', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_hf_models_model_provider'), table_name='hf_models')
    op.drop_index(op.f('ix_hf_models_model_id'), table_name='hf_models')
    op.create_index(op.f('ix_hf_models_hf_model_id'), 'hf_models', ['hf_model_id'], unique=True)
    op.drop_column('hf_models', 'description')
    op.drop_column('hf_models', 'model_url')
    op.drop_column('hf_models', 'model_provider')
    op.drop_column('hf_models', 'model_id')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
