"""Updated the chat and chatsMessages model

Revision ID: ef4c477edd16
Revises: 87f0479a2cea
Create Date: 2026-01-04 23:23:32.924697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef4c477edd16'
down_revision: Union[str, Sequence[str], None] = '87f0479a2cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_message_chat_id_fkey'), 'chat_message', type_='foreignkey')
    op.create_foreign_key(None, 'chat_message', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_message', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.create_foreign_key(op.f('chat_message_chat_id_fkey'), 'chat_message', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###
