"""added the number of images

Revision ID: fb093ad20c73
Revises: a3df4cf59093
Create Date: 2026-01-05 00:13:33.628009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb093ad20c73'
down_revision: Union[str, Sequence[str], None] = 'a3df4cf59093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('number_of_images', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'number_of_images')
    # ### end Alembic commands ###
